/*
 * Generated by OpenSSL util/mkerr.pl DO NOT EDIT
 */

#ifndef HEADER_SUOLAERR_H
# define HEADER_SUOLAERR_H

# define SUOLAerr(f, r) ERR_SUOLA_error((f), (r), __FILE__, __LINE__)


# ifdef  __cplusplus
extern "C" {
# endif
int ERR_load_SUOLA_strings(void);
void ERR_unload_SUOLA_strings(void);
void ERR_SUOLA_error(int function, int reason, char *file, int line);
# ifdef  __cplusplus
}
# endif

/*
 * SUOLA function codes.
 */
# define SUOLA_F_ASN1_ED25519_ITEM_VERIFY                 115
# define SUOLA_F_ASN1_GENERIC_CTRL                        108
# define SUOLA_F_ASN1_GENERIC_PRIV_DECODE                 110
# define SUOLA_F_ASN1_GENERIC_PRIV_ENCODE                 109
# define SUOLA_F_ASN1_GENERIC_PUB_DECODE                  112
# define SUOLA_F_ASN1_GENERIC_PUB_ENCODE                  111
# define SUOLA_F_ED25519_KEYGEN                           101
# define SUOLA_F_ED25519_SIGN                             103
# define SUOLA_F_ED25519_SK_TO_PK                         102
# define SUOLA_F_ED25519_VERIFY                           104
# define SUOLA_F_EVP_PKEY_CTX_ED25519_SET_PRIVATE         113
# define SUOLA_F_EVP_PKEY_ED25519_SET_PRIVATE             114
# define SUOLA_F_KEYPAIR_NEW                              100
# define SUOLA_F_X25519_DERIVE                            105
# define SUOLA_F_X25519_KEYGEN                            107
# define SUOLA_F_X25519_SK_TO_PK                          106

/*
 * SUOLA reason codes.
 */
# define SUOLA_R_BAD_SIGNATURE                            107
# define SUOLA_R_CANNOT_DERIVE_PK                         101
# define SUOLA_R_IMPLEMENTATION_BACKEND_UNEXPECTED_RETURN 100
# define SUOLA_R_INVALID_ENCODING                         110
# define SUOLA_R_INVALID_KEY                              104
# define SUOLA_R_INVALID_PEER_KEY                         105
# define SUOLA_R_INVALID_PRIVATE_KEY                      103
# define SUOLA_R_KEYS_NOT_SET                             102
# define SUOLA_R_MISSING_NID_DATA                         109
# define SUOLA_R_MISSING_PRIVATE_KEY                      106
# define SUOLA_R_RANDOM_NUMBER_GENERATION_FAILED          111
# define SUOLA_R_WRONG_LENGTH                             108

#endif
